import React from 'react';
import {AbsoluteFill,Html5Audio,interpolate,Sequence,spring,staticFile,useCurrentFrame,useVideoConfig} from 'remotion';
import {loadFont} from '@remotion/google-fonts/Inter';
loadFont('normal',{weights:['400','600','800'],subsets:['latin']});

export type LessonProps={
 title:string;hook:string;format:'long'|'short';
 sections:Array<{heading:string;body:string;accent?:string}>;
 callToAction:string;shortIndex?:number;
 shorts:Array<{hook:string;body:string;cta:string}>;
};
const colors={ink:'#eef8ff',muted:'#a9c4d8',blue:'#36dff6',orange:'#ff9b4b',bg:'#06101c'};

const Meter:React.FC<{accent:string}>=({accent})=>{const frame=useCurrentFrame();const turn=interpolate(frame,[0,90],[8,78],{extrapolateRight:'clamp'});return <div style={{width:420,height:230,border:`8px solid ${accent}`,borderBottom:0,borderRadius:'240px 240px 0 0',position:'relative',opacity:.82}}><div style={{position:'absolute',width:155,height:8,background:accent,left:205,bottom:0,transformOrigin:'0 50%',transform:`rotate(${turn-90}deg)`,borderRadius:8}}/><div style={{position:'absolute',width:24,height:24,borderRadius:'50%',background:'#fff',left:193,bottom:-8,boxShadow:`0 0 24px ${accent}`}}/></div>};
const Slide:React.FC<{heading:string;body:string;index:number;accent?:string}>=({heading,body,index,accent=colors.blue})=>{const frame=useCurrentFrame();const {fps}=useVideoConfig();const enter=spring({frame,fps,config:{damping:18}});return <AbsoluteFill style={{padding:'8%',justifyContent:'center',background:`radial-gradient(circle at 82% 18%,${accent}2d,transparent 32%),linear-gradient(145deg,#040a12,#0b1b2c)`,color:colors.ink,fontFamily:'Inter'}}><div style={{display:'grid',gridTemplateColumns:'1.5fr .7fr',gap:70,alignItems:'center'}}><div><div style={{fontSize:25,letterSpacing:5,color:accent,fontWeight:800}}>LEARN YOUR CAR · {String(index+1).padStart(2,'0')}</div><h2 style={{fontSize:78,lineHeight:1.04,margin:'24px 0',transform:`translateY(${(1-enter)*45}px)`,opacity:enter}}>{heading}</h2><p style={{fontSize:37,lineHeight:1.42,maxWidth:1180,color:colors.muted,margin:0}}>{body}</p></div><Meter accent={accent}/></div><div style={{position:'absolute',left:'8%',right:'8%',bottom:55,height:6,borderRadius:6,background:'#163044'}}><div style={{height:'100%',width:`${interpolate(frame,[0,150],[0,100],{extrapolateRight:'clamp'})}%`,background:accent,borderRadius:6}}/></div></AbsoluteFill>};

export const CarLesson:React.FC<LessonProps>=({title,hook,sections,callToAction})=>{const frame=useCurrentFrame();const {durationInFrames}=useVideoConfig();const intro=180,outro=180,segment=Math.floor((durationInFrames-intro-outro)/sections.length);return <AbsoluteFill style={{background:colors.bg}}><Html5Audio src={staticFile('audio/narration-long.wav')}/><Sequence durationInFrames={intro}><AbsoluteFill style={{padding:'8%',justifyContent:'center',color:colors.ink,fontFamily:'Inter',background:'radial-gradient(circle at 82% 18%,#36dff63b,transparent 34%),linear-gradient(145deg,#030810,#0b1b2d)'}}><div style={{fontSize:27,color:colors.orange,fontWeight:800,letterSpacing:5}}>LEARN YOUR CAR</div><h1 style={{fontSize:92,lineHeight:1,margin:'30px 0',maxWidth:1500,opacity:interpolate(frame,[0,22],[0,1],{extrapolateRight:'clamp'})}}>{title}</h1><p style={{fontSize:42,color:colors.muted,maxWidth:1400}}>{hook}</p></AbsoluteFill></Sequence>{sections.map((section,index)=><Sequence key={section.heading} from={intro+index*segment} durationInFrames={segment} premountFor={30}><Slide {...section} index={index}/></Sequence>)}<Sequence from={durationInFrames-outro} durationInFrames={outro}><AbsoluteFill style={{padding:'8%',justifyContent:'center',alignItems:'center',textAlign:'center',color:colors.ink,fontFamily:'Inter',background:'radial-gradient(circle,#36dff62c,transparent 42%),#06101c'}}><div style={{fontSize:29,letterSpacing:6,color:colors.orange,fontWeight:800}}>YOUR NEXT CHECK</div><h2 style={{fontSize:78,maxWidth:1450}}>{callToAction}</h2></AbsoluteFill></Sequence></AbsoluteFill>};

export const CarShort:React.FC<LessonProps>=({shorts,shortIndex=0})=>{const frame=useCurrentFrame(),item=shorts[shortIndex]||shorts[0];return <AbsoluteFill style={{padding:'12% 9%',justifyContent:'center',fontFamily:'Inter',color:colors.ink,textAlign:'center',background:'radial-gradient(circle at 50% 18%,#36dff64a,transparent 30%),linear-gradient(165deg,#030812,#0a2032)'}}><Html5Audio src={staticFile(`audio/short-${shortIndex+1}.wav`)}/><div style={{fontSize:28,letterSpacing:5,color:colors.orange,fontWeight:800}}>LEARN YOUR CAR</div><h1 style={{fontSize:82,lineHeight:1.03,margin:'40px 0',transform:`scale(${interpolate(frame,[0,20],[.88,1],{extrapolateRight:'clamp'})})`}}>{item.hook}</h1><div style={{width:230,height:230,borderRadius:'50%',margin:'15px auto 45px',display:'grid',placeItems:'center',border:`10px solid ${colors.blue}`,boxShadow:`0 0 55px ${colors.blue}55`,fontSize:86,fontWeight:800}}>{shortIndex+1}</div><p style={{fontSize:42,lineHeight:1.38,color:colors.muted}}>{item.body}</p><div style={{marginTop:45,padding:24,border:`2px solid ${colors.orange}`,borderRadius:18,fontSize:34,fontWeight:700}}>{item.cta}</div></AbsoluteFill>};

export const Thumbnail:React.FC<LessonProps>=({title})=><AbsoluteFill style={{fontFamily:'Inter',color:'#fff',background:'radial-gradient(circle at 82% 20%,#ff9b4b55,transparent 25%),radial-gradient(circle at 12% 80%,#36dff655,transparent 32%),#06101c',padding:100,justifyContent:'center'}}><div style={{fontSize:30,letterSpacing:7,color:colors.orange,fontWeight:800}}>LEARN YOUR CAR</div><div style={{fontSize:104,lineHeight:.98,fontWeight:800,maxWidth:1500,marginTop:30}}>{title}</div><div style={{position:'absolute',right:105,bottom:90,width:330,height:330,borderRadius:'50%',border:`22px solid ${colors.blue}`,boxShadow:`0 0 70px ${colors.blue}77`,display:'grid',placeItems:'center',fontSize:118,fontWeight:800}}>?</div></AbsoluteFill>;
